openapi: 3.0.1
info:
  title: Products API
  description: API to manage products
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/products:
    get:
      summary: Get all users
      description: Retrieve a list of all users
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    type: array
                    items:
                      $ref: "#/components/schemas/Product"

components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        stock:
          type: string
